#!/bin/bash
#SBATCH --job-name=China             # Job name
#SBATCH --array=1-256                # Number of MPI tasks (i.e. processes)
#SBATCH --cpus-per-task=1            # Number of cores per MPI task 
#SBATCH --nodes=1                    # Maximum number of nodes to be allocated
#SBATCH --ntasks-per-node=1          # Maximum number of tasks on each node
#SBATCH --time=1:00:00              # Time limit hrs:min:sec
#SBATCH -o ./slurm_output/output.%a.out


date;hostname;pwd
source /home/groups/jblanche/DR-Conditional-Port-Opt/port-opt-env/bin/activate
REG=0.1
REG_ARR=(1 2 5)
GAMMA_Q_ARR=(0.1 0.25 0.5)
RHO_Q_ARR=(0.05 0.1 0.25)
EPS_ARR=(0.1 0.2 0.5) 
RHO_DIV_ARR=(1.1 1.2)
DELTA_ARR=(0.1 0.2 0.5)
P_ARR=(2)

for reg in "${REG_ARR[@]}"; do
    python3 port-opt-exp.py --solver=MV --SEED=$SLURM_ARRAY_TASK_ID --reg_params=$reg
done;
echo "MV finish"

for delta in "${DELTA_ARR[@]}"; do
    for p in "${P_ARR[@]}"; do
        python3 port-opt-exp.py --solver=DRMV --SEED=$SLURM_ARRAY_TASK_ID --reg_params=$REG --delta=$delta --p=$p
    done;
done;
echo "DRMV finish"